sudo: true
services:
  - docker
git:
  depth: false
branches:
  only:
  - master
if: (commit_message =~ ^daily) AND (branch = master)
before_install:
- chmod +x docker/merge.sh
- docker pull synker/xmltv_merge:latest
- docker run -it -v "${PWD}:/work" -e GITHUB_API_TOKEN=${GITHUB_API_TOKEN} synker/xmltv_merge:0.0.3 /bin/bash -c "dos2unix docker/merge.sh && chmod +x docker/merge.sh && docker/merge.sh '*.xmltv'"
- git remote add origin2 https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
- git add merge.tar.gz && git commit -m "compression and mergin xmltv files and pushing them to GITHUB" && git push origin2 HEAD:master

notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
