language: minimal
script: 
  - tar zcvf guide.tar.gz *.xmltv
  - DATE=`date '+%Y-%m-%d %H:%M:%S'`
after_success:
  - git status
  - git remote
  - git remote add origin https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
  - git config user.email tunisienheni@outlook.com
  - git config user.name Fazzani
  - git add --all && git commit -m "Daily update from travis" && git push origin HEAD:master
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: "guide.tar.gz"
  skip_cleanup: true
