sudo: true
services:
  - docker
git:
  depth: false
branches:
  only:
  - master
if: (commit_message =~ ^daily) AND (branch = master)
before_install:
- chmod +x docker/merge.sh
- docker pull synker/xmltv_merge:latest
- docker run -d -v .:/work synker/xmltv_merge

notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
