sudo: true
git:
  depth: false
branches:
  only:
  - master
if: (commit_message =~ ^daily) AND (branch = master)
script:
 - tar zcvf guide.tar.gz merge.xmltv
 - git status
 - git remote add origin2 https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
 - git add guide.tar.gz && git commit -m "Pushing compressed version to GITHUB from travis" && git push origin2 HEAD:master
notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
