language: minimal
sudo: true
dist: trusty
if: (commit_message =~ ^daily) AND (branch = master)
before_install:
 - sudo apt-get --yes install xmltv-util
 - sudo chmod +x merge.sh
script: 
 - ./merge.sh "./*.xmltv"
 - git status
 - git remote add origin2 https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
 - git add --all && git commit -m "Pushing compressed version to GIYHUB from travis" && git push origin2 HEAD:master
notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
