language: minimal
script: 
  - tar zcvf guide.tar.gz *.xmltv
  - DATE=`date '+%Y-%m-%d %H:%M:%S'`
after_success:
  - git status
  - git remote add origin2 https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
  - git add --all && git commit -m ${DATE}": Daily update from travis" && git push origin2 HEAD:master
