language: ruby
rvm:
  - 2.0.0
script: 
  - tar zcvf guide.tar.gz *.xmltv
  - DATE=`date '+%Y-%m-%d %H:%M:%S'`
after_success:
  - git status
  - git remote add origin https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
  - git add --all && git commit -m "$DATE: Daily update from travis" && git push  
deploy:
  provider: releases
  api_key: $GITHUB_API_TOKEN
  file: "guide.tar.gz"
  skip_cleanup: true
