language: minimal
sudo: true
jobs:
  include: 
    - stage: Merging & Compression xmltv files
      before_install:
       - sudo apt-get install xmltv-util
      script: 
       - chmod +x merge.sh && ./merge.sh
       - git status
       - git remote add origin2 https://${GITHUB_API_TOKEN}@github.com/fazzani/xmltv.git > /dev/null 2>&1
       - git add --all && git commit -m "Pushing compressed version to GIYHUB from travis" && git push origin2 HEAD:master
      if: (commit_message =~ ^daily) AND (branch = master)
notifications:
  email:
    recipients:
      - tunisienheni@gmail.com
    on_success: change
    on_failure: change
