FROM debian 
ENV GITHUB_API_TOKEN xxxx

RUN apt-get -qq -y update && apt-get -y install xmltv-util

WORKDIR /work

VOLUME ["/work"]
RUN sudo chmod +x /work/docker/merge.sh
ENTRYPOINT /work/docker/merge.sh *.xmltv
